# Site settings
title: Amin N Ali
description: Analytics Pro & Music Aficionado
lang: en-US 
timezone: America/Los_Angeles




# Profile settings
author:
  name: Amin N Ali
  bio: Data Analytics professional and Indie Music aficionado
  image: /assets/profile.png
  image2: /assets/profile2.jpg
  icon: /assets/favicon.ico
  email: mail[at]aminn[dot]ca
  mastodon: https://mathstodon.xyz/@aminn04
  spotify: https://open.spotify.com/user/aminn04 
  instagram: https://instagram.com/aminn04
  github: https://github.com/aminn04
  linkedin: https://www.linkedin.com/in/aminnali/
  
  
# URL settings
url: https://aminn.ca
baseurl: /
umami_analytics: # leave it blank if not wish


# Build settings
theme: minima
sass:
  style: compressed
plugins:
  # - jekyll-feed
  - jekyll-sitemap
  - jekyll-email-protect


# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - .vscode/
  - .github/
